# Generated by Django 4.0.1 on 2022-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommonBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="favorite course"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="notification frecuency"
                    ),
                ),
            ],
            options={
                "verbose_name": "business",
                "verbose_name_plural": "businesses",
                "db_table": "common_business_data",
            },
        ),
    ]
