# Generated by Django 4.0.1 on 2022-07-18 18:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.CharField(default='', max_length=255, verbose_name='services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerrepresentant',
            name='local_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='local phone number'),
        ),
    ]
