# Generated by Django 4.0.1 on 2022-07-09 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRepresentant',
            fields=[
                ('commonclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.commonclient')),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='notification frecuency')),
                ('business_email', models.EmailField(max_length=254, verbose_name='business_email')),
            ],
            options={
                'verbose_name': 'provider_representant',
                'verbose_name_plural': 'provider_representants',
                'db_table': 'provider_representant',
            },
            bases=('client.commonclient',),
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('commonbusiness_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='business.commonbusiness')),
                ('services', models.CharField(max_length=255, verbose_name='services')),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'db_table': 'businesses',
            },
            bases=('business.commonbusiness',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('commonclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.commonclient')),
                ('document_id', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='your document id is not well formatted', regex='^[eEvVjJ]\\d+$')], verbose_name='document id (cedula/rif)')),
                ('contract_modality', models.CharField(max_length=255, verbose_name='contract modality')),
                ('business_email', models.EmailField(max_length=254, verbose_name='business_email')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='business.commonbusiness', verbose_name='Business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
            bases=('client.commonclient',),
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('commonclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='client.commonclient')),
                ('name', models.CharField(max_length=255, verbose_name='favorite course')),
                ('email', models.EmailField(max_length=254, verbose_name='notification frecuency')),
                ('representant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.providerrepresentant')),
                ('business', models.ManyToManyField(related_name='providers', to='business.Business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'provider',
                'verbose_name_plural': 'providers',
                'db_table': 'providers',
            },
            bases=('client.commonclient',),
        ),
    ]
