# Generated by Django 4.0.1 on 2022-07-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_employee_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
        migrations.AddField(
            model_name='provider',
            name='services',
            field=models.CharField(default='', max_length=255, verbose_name='services'),
            preserve_default=False,
        ),
    ]
