# Generated by Django 4.0.1 on 2022-07-18 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0003_remove_employee_services_provider_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerrepresentant',
            name='charge',
        ),
        migrations.RemoveField(
            model_name='providerrepresentant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='providerrepresentant',
            name='personal_email',
        ),
        migrations.AddField(
            model_name='providerrepresentant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='provider_representant', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
