# Generated by Django 4.0.1 on 2022-07-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0004_alter_commonbusiness_tax_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonbusiness",
            name="website",
            field=models.URLField(
                default="a@b.com", max_length=255, verbose_name="website"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="commonbusiness",
            name="tax_id",
            field=models.CharField(max_length=255, verbose_name="tax id"),
        ),
    ]
