# Generated by Django 4.0.1 on 2022-07-09 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "fav_course",
                    models.CharField(max_length=255, verbose_name="favorite course"),
                ),
                (
                    "notification_frecuency",
                    models.CharField(
                        max_length=255, verbose_name="notification frecuency"
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "db_table": "common_client_data",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "iso_3166_1_a2",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISO 3166-1 alpha-2",
                    ),
                ),
                (
                    "iso_3166_1_a3",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="ISO 3166-1 alpha-3"
                    ),
                ),
                (
                    "iso_3166_1_numeric",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="ISO 3166-1 numeric"
                    ),
                ),
                (
                    "printable_name",
                    models.CharField(
                        db_index=True, max_length=128, verbose_name="Country name"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="Official name"),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Higher the number, higher the country in the list.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_shipping_country",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is shipping country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ("-display_order", "printable_name"),
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="social name")),
                (
                    "value",
                    models.CharField(max_length=255, verbose_name="social value"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="client.commonclient",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Socials",
                "db_table": "socials",
            },
        ),
        migrations.CreateModel(
            name="ParticularClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255, verbose_name="type")),
                ("company", models.CharField(max_length=255, verbose_name="company")),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="whatsapp"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "particular client",
                "verbose_name_plural": "particular clients",
                "db_table": "particular_clients",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        max_length=255, verbose_name="First line of address"
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Second line of address",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="State/County"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="client.commonclient",
                        verbose_name="Country",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social",
                "verbose_name_plural": "Socials",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "commonclient_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="client.commonclient",
                    ),
                ),
                (
                    "offered_services",
                    models.CharField(max_length=255, verbose_name="offered services"),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "business"), ("model", "Business")),
                            models.Q(
                                ("app_label", "client"), ("model", "ParticularClient")
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "verbose_name_plural": "clients",
                "db_table": "clients",
            },
            bases=("client.commonclient",),
        ),
    ]
